### ISSUE TITLE
Error after loading project

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojpch-performance-test#1]
I redid the setting up of the latest version and on the first run got an error

Did run ojp_performance_tests.py from pycharm

```
ervice                                      number of tests                                                   calc. time [ms]
environment  request type        total         ok     not_ok        min    average        p50        p90        p95        max
TRIAS2020    TRIAS2020TR            10         10          0        117        814        238       2508       2734       2734
PROD         TR                     10         10          0        118       2424        434       7265      10344      10344
PROD         LIR                    10         10          0         86        104         93        130        171        171
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\ojpch-performance-test1\ojp_performance_tests.py", line 522, in <module>
    process()
  File "C:\Users\ue71603\MG_Daten\github\ojpch-performance-test1\ojp_performance_tests.py", line 518, in process
    copy_log_file(test_directory)
  File "C:\Users\ue71603\MG_Daten\github\ojpch-performance-test1\ojp_performance_tests.py", line 496, in copy_log_file
    shutil.copy2(LOG_FILE, os.path.join(config.OUTPUT, test_directory, '_log.txt'))
  File "C:\Users\ue71603\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\ue71603\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './output/latest_log.log'
```

Process finished with exit code 1

**Comment by markus-meier-sbb** [comment]
Fixed with commit https://github.com/openTdataCH/ojpch-performance-test/commit/060720041ec80005f0306b633e56478552e92307
--> new branch "Work".
